trigger: none

pool: bkagentlinux

stages:
- stage: buildStageScanStage
  jobs:
  - job: buildJob
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-acr'
        command: 'login'
    - task: trivy@1
      inputs:
        version: 'latest'
        loginDockerConfig: true
        image: 'microtodoui:latest'
        severities: 'CRITICAL,HIGH,MEDIUM,LOW,UNKNOWN'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'trivyScanReport'
        publishLocation: 'Container'
    - task: Docker@2
      inputs:
        containerRegistry: 'docker-acr'
        repository: 'MicroTodoUI'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest
# - stage: DeployStage
#   jobs:
#   - job: DeployJob
#     steps:
#     - task: KubernetesManifest@1
#       inputs:
#         action: 'deploy'
#         connectionType: 'kubernetesServiceConnection'
#         kubernetesServiceConnection: 'humara-aks'
#         namespace: 'bipin'
#         manifests: 'mainefests/*.yaml'
